version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions-all:
        patterns:
          - "*"

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      cargo-minor-patch:
        update-types:
          - "minor"
          - "patch"
        patterns:
          - "*"
      cargo-major:
        update-types:
          - "major"
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directories:
      - "/runtime"
      - "/editor-support/vsc/compact"
      - "/tests-e2e"
      - "/test-center"
      - "/test-src-maps"
      - "/debug-test"
      - "/nix/dry-install"
    schedule:
      interval: "weekly"
    groups:
      npm-minor-patch:
        update-types:
          - "minor"
          - "patch"
        patterns:
          - "*"
      npm-major:
        update-types:
          - "major"
        patterns:
          - "*"

#  - package-ecosystem: "docker"
#    directory: "/"
#    schedule:
#      interval: "weekly"
#    cooldown:
#      default-days: 7
#
#registries:
#   github:
#     type: git
#     url: https://github.com
#     username: MidnightCI
#     password: ${{ secrets.MIDNIGHTCI_REPO }}
