// SPDX-License-Identifier: Apache-2.0
// Generated by compactc. Do not edit by hand.

#![allow(clippy::all, dead_code, unused_imports, unused_variables)]

use compact_runtime::*;
use std::marker::PhantomData;

compact_runtime::check_runtime_version!("0.16.100");

pub trait Witnesses<PS> {
}
impl<PS> Witnesses<PS> for NoWitnesses {}

pub struct Contract<PS, W = NoWitnesses>
where
    W: Witnesses<PS>,
{
    pub witnesses: W,
    _ps: PhantomData<PS>,
}

impl<PS, W> Contract<PS, W>
where
    W: Witnesses<PS>,
{
    pub fn new(witnesses: W) -> Self {
        Self { witnesses, _ps: PhantomData }
    }
    pub fn initial_state(
        &self,
        ctx: ConstructorContext<PS>,
    ) -> Result<ConstructorResult<PS>, CompactError> {
        let sv = new_array(vec![
            new_map(),
        ]);
        let state = ChargedState::new(sv);
        let qctx = QueryContext::new(state, ContractAddress::default());
        Ok(ConstructorResult {
            current_contract_state: qctx.state,
            current_private_state: ctx.initial_private_state,
            current_zswap_local_state: ctx.empty_zswap_local_state,
        })
    }

    pub fn put(
        &self,
        ctx: CircuitContext<PS>,
        k: Fr,
        v: Fr,
    ) -> Result<CircuitResults<PS, ()>, CompactError> {
        let ops = OpProgramVerify::<DefaultDB>::new()
            .idx_at_index(0u8, true)
            .push(false, new_cell(k))
            .push(true, new_cell(v))
            .ins(false, 1)
            .ins(true, 1)
            .build();

        let results = query_for_verify(
            &ctx.current_query_context,
            &ops,
            ctx.gas_limit.clone(),
            &ctx.cost_model,
        )?;

        Ok(CircuitResults {
            result: (),
            context: CircuitContext {
                current_query_context: results.context,
                ..ctx
            },
            gas_cost: results.gas_cost,
        })
    }

}

pub struct Ledger<'a, D: DB = DefaultDB> {
    state: &'a ChargedState<D>,
}

pub fn ledger<D: DB>(state: &ChargedState<D>) -> Ledger<'_, D> {
    Ledger { state }
}

impl<'a, D: DB> Ledger<'a, D> {
}

pub mod pure_circuits {
}
