// SPDX-License-Identifier: Apache-2.0
// Generated by compactc. Do not edit by hand.

#![allow(clippy::all, dead_code, unused_imports, unused_variables)]

use compact_runtime::*;
use std::marker::PhantomData;

compact_runtime::check_runtime_version!("0.16.100");

#[derive(Clone, Debug, PartialEq, Eq, Default)]
pub struct MerkleTreeDigest {
    pub field: Fr,
}
impl Aligned for MerkleTreeDigest {
    fn alignment() -> Alignment {
        Alignment::concat([&<Fr as Aligned>::alignment()])
    }
}
impl FieldRepr for MerkleTreeDigest {
    fn field_repr<W: MemWrite<Fr>>(&self, writer: &mut W) {
        self.field.field_repr(writer);
    }
    fn field_size(&self) -> usize {
        self.field.field_size()
    }
}
impl FromFieldRepr for MerkleTreeDigest {
    const FIELD_SIZE: usize = <Fr as FromFieldRepr>::FIELD_SIZE;
    fn from_field_repr(r: &[Fr]) -> Option<Self> {
        if r.len() < Self::FIELD_SIZE { return None; }
        let mut _offset = 0usize;
        let field = <Fr as FromFieldRepr>::from_field_repr(&r[_offset.._offset + <Fr as FromFieldRepr>::FIELD_SIZE])?;
        _offset += <Fr as FromFieldRepr>::FIELD_SIZE;
        let _ = _offset;
        Some(MerkleTreeDigest { field })
    }
}
impl From<MerkleTreeDigest> for compact_runtime::Value {
    fn from(s: MerkleTreeDigest) -> compact_runtime::Value {
        let mut _v: Vec<compact_runtime::Value> = Vec::new();
        _v.push(compact_runtime::Value::from(s.field));
        compact_runtime::Value::concat(_v.iter())
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
#[repr(u8)]
pub enum PermissibleVotes {
    yes = 0,
    no = 1,
}
impl Aligned for PermissibleVotes {
    fn alignment() -> Alignment {
        u8::alignment()
    }
}
impl FieldRepr for PermissibleVotes {
    fn field_repr<W: MemWrite<Fr>>(&self, writer: &mut W) {
        (*self as u8).field_repr(writer);
    }
    fn field_size(&self) -> usize { 1 }
}
impl FromFieldRepr for PermissibleVotes {
    const FIELD_SIZE: usize = 1;
    fn from_field_repr(r: &[Fr]) -> Option<Self> {
        let n = u8::from_field_repr(r)?;
        match n {
            0 => Some(Self::yes),
            1 => Some(Self::no),
            _ => None,
        }
    }
}
#[derive(Clone, Debug, PartialEq, Eq, Default)]
pub struct LeafPreimage {
    pub domain_sep: [u8; 6],
    pub data: [u8; 32],
}
impl Aligned for LeafPreimage {
    fn alignment() -> Alignment {
        Alignment::concat([&<[u8; 6] as Aligned>::alignment(), &<[u8; 32] as Aligned>::alignment()])
    }
}
impl FieldRepr for LeafPreimage {
    fn field_repr<W: MemWrite<Fr>>(&self, writer: &mut W) {
        self.domain_sep.field_repr(writer);
        self.data.field_repr(writer);
    }
    fn field_size(&self) -> usize {
        self.domain_sep.field_size() + self.data.field_size()
    }
}
impl FromFieldRepr for LeafPreimage {
    const FIELD_SIZE: usize = compact_runtime::bytes_field_size(6) + <[u8; 32] as FromFieldRepr>::FIELD_SIZE;
    fn from_field_repr(r: &[Fr]) -> Option<Self> {
        if r.len() < Self::FIELD_SIZE { return None; }
        let mut _offset = 0usize;
        let domain_sep = compact_runtime::bytes_from_field_repr::<6>(&r[_offset.._offset + compact_runtime::bytes_field_size(6)])?;
        _offset += compact_runtime::bytes_field_size(6);
        let data = <[u8; 32] as FromFieldRepr>::from_field_repr(&r[_offset.._offset + <[u8; 32] as FromFieldRepr>::FIELD_SIZE])?;
        _offset += <[u8; 32] as FromFieldRepr>::FIELD_SIZE;
        let _ = _offset;
        Some(LeafPreimage { domain_sep, data })
    }
}
impl From<LeafPreimage> for compact_runtime::Value {
    fn from(s: LeafPreimage) -> compact_runtime::Value {
        let mut _v: Vec<compact_runtime::Value> = Vec::new();
        _v.push(compact_runtime::Value::from(s.domain_sep));
        _v.push(compact_runtime::Value::from(s.data));
        compact_runtime::Value::concat(_v.iter())
    }
}

#[derive(Clone, Debug, PartialEq, Eq, Default)]
pub struct MerkleTreePath {
    pub leaf: [u8; 32],
    pub path: [MerkleTreePathEntry; 10],
}
impl Aligned for MerkleTreePath {
    fn alignment() -> Alignment {
        Alignment::concat([&<[u8; 32] as Aligned>::alignment(), &<MerkleTreePathEntry as Aligned>::alignment(), &<MerkleTreePathEntry as Aligned>::alignment(), &<MerkleTreePathEntry as Aligned>::alignment(), &<MerkleTreePathEntry as Aligned>::alignment(), &<MerkleTreePathEntry as Aligned>::alignment(), &<MerkleTreePathEntry as Aligned>::alignment(), &<MerkleTreePathEntry as Aligned>::alignment(), &<MerkleTreePathEntry as Aligned>::alignment(), &<MerkleTreePathEntry as Aligned>::alignment(), &<MerkleTreePathEntry as Aligned>::alignment()])
    }
}
impl FieldRepr for MerkleTreePath {
    fn field_repr<W: MemWrite<Fr>>(&self, writer: &mut W) {
        self.leaf.field_repr(writer);
        for _e in self.path.iter() { _e.field_repr(writer); }
    }
    fn field_size(&self) -> usize {
        self.leaf.field_size() + self.path.iter().map(|e| e.field_size()).sum::<usize>()
    }
}
impl FromFieldRepr for MerkleTreePath {
    const FIELD_SIZE: usize = <[u8; 32] as FromFieldRepr>::FIELD_SIZE + <MerkleTreePathEntry as FromFieldRepr>::FIELD_SIZE * 10;
    fn from_field_repr(r: &[Fr]) -> Option<Self> {
        if r.len() < Self::FIELD_SIZE { return None; }
        let mut _offset = 0usize;
        let leaf = <[u8; 32] as FromFieldRepr>::from_field_repr(&r[_offset.._offset + <[u8; 32] as FromFieldRepr>::FIELD_SIZE])?;
        _offset += <[u8; 32] as FromFieldRepr>::FIELD_SIZE;
        let path = compact_runtime::array_from_field_repr::<MerkleTreePathEntry, 10>(&r[_offset.._offset + <MerkleTreePathEntry as FromFieldRepr>::FIELD_SIZE * 10], <MerkleTreePathEntry as FromFieldRepr>::FIELD_SIZE)?;
        _offset += <MerkleTreePathEntry as FromFieldRepr>::FIELD_SIZE * 10;
        let _ = _offset;
        Some(MerkleTreePath { leaf, path })
    }
}
impl From<MerkleTreePath> for compact_runtime::Value {
    fn from(s: MerkleTreePath) -> compact_runtime::Value {
        let mut _v: Vec<compact_runtime::Value> = Vec::new();
        _v.push(compact_runtime::Value::from(s.leaf));
        for _e in s.path.iter() { _v.push(compact_runtime::Value::from(_e.clone())); }
        compact_runtime::Value::concat(_v.iter())
    }
}

#[derive(Clone, Debug, PartialEq, Eq, Default)]
pub struct MerkleTreePathEntry {
    pub sibling: MerkleTreeDigest,
    pub goes_left: bool,
}
impl Aligned for MerkleTreePathEntry {
    fn alignment() -> Alignment {
        Alignment::concat([&<MerkleTreeDigest as Aligned>::alignment(), &<bool as Aligned>::alignment()])
    }
}
impl FieldRepr for MerkleTreePathEntry {
    fn field_repr<W: MemWrite<Fr>>(&self, writer: &mut W) {
        self.sibling.field_repr(writer);
        self.goes_left.field_repr(writer);
    }
    fn field_size(&self) -> usize {
        self.sibling.field_size() + self.goes_left.field_size()
    }
}
impl FromFieldRepr for MerkleTreePathEntry {
    const FIELD_SIZE: usize = <MerkleTreeDigest as FromFieldRepr>::FIELD_SIZE + <bool as FromFieldRepr>::FIELD_SIZE;
    fn from_field_repr(r: &[Fr]) -> Option<Self> {
        if r.len() < Self::FIELD_SIZE { return None; }
        let mut _offset = 0usize;
        let sibling = <MerkleTreeDigest as FromFieldRepr>::from_field_repr(&r[_offset.._offset + <MerkleTreeDigest as FromFieldRepr>::FIELD_SIZE])?;
        _offset += <MerkleTreeDigest as FromFieldRepr>::FIELD_SIZE;
        let goes_left = <bool as FromFieldRepr>::from_field_repr(&r[_offset.._offset + <bool as FromFieldRepr>::FIELD_SIZE])?;
        _offset += <bool as FromFieldRepr>::FIELD_SIZE;
        let _ = _offset;
        Some(MerkleTreePathEntry { sibling, goes_left })
    }
}
impl From<MerkleTreePathEntry> for compact_runtime::Value {
    fn from(s: MerkleTreePathEntry) -> compact_runtime::Value {
        let mut _v: Vec<compact_runtime::Value> = Vec::new();
        _v.push(compact_runtime::Value::from(s.sibling));
        _v.push(compact_runtime::Value::from(s.goes_left));
        compact_runtime::Value::concat(_v.iter())
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
#[repr(u8)]
pub enum PrivateState {
    initial = 0,
    committed = 1,
    revealed = 2,
}
impl Aligned for PrivateState {
    fn alignment() -> Alignment {
        u8::alignment()
    }
}
impl FieldRepr for PrivateState {
    fn field_repr<W: MemWrite<Fr>>(&self, writer: &mut W) {
        (*self as u8).field_repr(writer);
    }
    fn field_size(&self) -> usize { 1 }
}
impl FromFieldRepr for PrivateState {
    const FIELD_SIZE: usize = 1;
    fn from_field_repr(r: &[Fr]) -> Option<Self> {
        let n = u8::from_field_repr(r)?;
        match n {
            0 => Some(Self::initial),
            1 => Some(Self::committed),
            2 => Some(Self::revealed),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
#[repr(u8)]
pub enum PublicState {
    setup = 0,
    commit = 1,
    reveal = 2,
    r#final = 3,
}
impl Aligned for PublicState {
    fn alignment() -> Alignment {
        u8::alignment()
    }
}
impl FieldRepr for PublicState {
    fn field_repr<W: MemWrite<Fr>>(&self, writer: &mut W) {
        (*self as u8).field_repr(writer);
    }
    fn field_size(&self) -> usize { 1 }
}
impl FromFieldRepr for PublicState {
    const FIELD_SIZE: usize = 1;
    fn from_field_repr(r: &[Fr]) -> Option<Self> {
        let n = u8::from_field_repr(r)?;
        match n {
            0 => Some(Self::setup),
            1 => Some(Self::commit),
            2 => Some(Self::reveal),
            3 => Some(Self::r#final),
            _ => None,
        }
    }
}

pub trait Witnesses<PS> {
    fn private_secret_key<'a>(&self, ctx: &WitnessContext<Ledger<'a>, PS>) -> (PS, [u8; 32]);
    fn private_state<'a>(&self, ctx: &WitnessContext<Ledger<'a>, PS>) -> (PS, PrivateState);
    fn private_state_advance<'a>(&self, ctx: &WitnessContext<Ledger<'a>, PS>) -> (PS, ());
    fn private_vote_record<'a>(&self, ctx: &WitnessContext<Ledger<'a>, PS>, ballot: PermissibleVotes) -> (PS, ());
    fn private_vote<'a>(&self, ctx: &WitnessContext<Ledger<'a>, PS>) -> (PS, PermissibleVotes);
    fn context_eligible_voters_path_of<'a>(&self, ctx: &WitnessContext<Ledger<'a>, PS>, pk: [u8; 32]) -> (PS, Maybe<MerkleTreePath>);
    fn context_committed_votes_path_of<'a>(&self, ctx: &WitnessContext<Ledger<'a>, PS>, cm: [u8; 32]) -> (PS, Maybe<MerkleTreePath>);
}

pub struct Contract<PS, W = NoWitnesses>
where
    W: Witnesses<PS>,
{
    pub witnesses: W,
    _ps: PhantomData<PS>,
}

impl<PS, W> Contract<PS, W>
where
    W: Witnesses<PS>,
{
    pub fn new(witnesses: W) -> Self {
        Self { witnesses, _ps: PhantomData }
    }
    pub fn initial_state(
        &self,
        ctx: ConstructorContext<PS>,
    ) -> Result<ConstructorResult<PS>, CompactError> {
        let sv = new_array(vec![
            new_cell([0u8; 32]),
            new_cell(0u8),
            new_cell(Maybe::<compact_runtime::std_lib::OpaqueString>::default()),
            new_cell(0u64),
            new_cell(0u64),
            new_merkle_tree(10),
            new_merkle_tree(10),
            new_map(),
            new_map(),
        ]);
        let state = ChargedState::new(sv);
        let qctx = QueryContext::new(state, ContractAddress::default());
        Ok(ConstructorResult {
            current_contract_state: qctx.state,
            current_private_state: ctx.initial_private_state,
            current_zswap_local_state: ctx.empty_zswap_local_state,
        })
    }

    pub fn vote_commit(
        &self,
        ctx: CircuitContext<PS>,
        ballot: PermissibleVotes,
    ) -> Result<CircuitResults<PS, ()>, CompactError> {
        unimplemented!("M3-I3: circuit body emission for vote$commit")
    }

    pub fn vote_reveal(
        &self,
        ctx: CircuitContext<PS>,
    ) -> Result<CircuitResults<PS, ()>, CompactError> {
        unimplemented!("M3-I3: circuit body emission for vote$reveal")
    }

    pub fn advance(
        &self,
        ctx: CircuitContext<PS>,
    ) -> Result<CircuitResults<PS, ()>, CompactError> {
        unimplemented!("M3-I3: circuit body emission for advance")
    }

    pub fn set_topic(
        &self,
        ctx: CircuitContext<PS>,
        t: compact_runtime::std_lib::OpaqueString,
    ) -> Result<CircuitResults<PS, ()>, CompactError> {
        unimplemented!("M3-I3: circuit body emission for set_topic")
    }

    pub fn add_voter(
        &self,
        ctx: CircuitContext<PS>,
        pk: [u8; 32],
    ) -> Result<CircuitResults<PS, ()>, CompactError> {
        unimplemented!("M3-I3: circuit body emission for add_voter")
    }

}

pub struct Ledger<'a, D: DB = DefaultDB> {
    state: &'a ChargedState<D>,
}

pub fn ledger<D: DB>(state: &ChargedState<D>) -> Ledger<'_, D> {
    Ledger { state }
}

impl<'a, D: DB> Ledger<'a, D> {
}

pub mod pure_circuits {
    use super::*;

    pub(crate) fn ballot_repr(ballot: PermissibleVotes) -> [u8; 32] {
        unimplemented!("M3-I3: pure circuit body emission for ballot_repr")
    }

    pub(crate) fn successor(state: PublicState) -> PublicState {
        unimplemented!("M3-I3: pure circuit body emission for successor")
    }

    pub(crate) fn commitment_nullifier(sk: [u8; 32]) -> [u8; 32] {
        compact_runtime::persistent_hash(&[[108u8, 97, 114, 101, 115, 58, 101, 108, 101, 99, 116, 105, 111, 110, 58, 99, 109, 45, 110, 117, 108, 58, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], sk].concat()).0
    }

    pub(crate) fn reveal_nullifier(sk: [u8; 32]) -> [u8; 32] {
        compact_runtime::persistent_hash(&[[108u8, 97, 114, 101, 115, 58, 101, 108, 101, 99, 116, 105, 111, 110, 58, 114, 118, 45, 110, 117, 108, 58, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], sk].concat()).0
    }

    pub(crate) fn public_key(sk: [u8; 32]) -> [u8; 32] {
        compact_runtime::persistent_hash(&[[108u8, 97, 114, 101, 115, 58, 101, 108, 101, 99, 116, 105, 111, 110, 58, 112, 107, 58, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], sk].concat()).0
    }

    pub(crate) fn commit_with_sk(ballot: [u8; 32], sk: [u8; 32]) -> [u8; 32] {
        compact_runtime::persistent_hash(&[ballot, sk].concat()).0
    }

}
