// SPDX-License-Identifier: Apache-2.0
// Generated by compactc. Do not edit by hand.

#![allow(clippy::all, dead_code, unused_imports, unused_variables)]

use compact_runtime::*;
use std::marker::PhantomData;

compact_runtime::check_runtime_version!("0.16.100");

#[derive(Clone, Debug, PartialEq, Eq, Default)]
pub struct MerkleTreeDigest {
    pub field: Fr,
}
impl Aligned for MerkleTreeDigest {
    fn alignment() -> Alignment {
        Alignment::concat([&<Fr as Aligned>::alignment()])
    }
}
impl FieldRepr for MerkleTreeDigest {
    fn field_repr<W: MemWrite<Fr>>(&self, writer: &mut W) {
        self.field.field_repr(writer);
    }
    fn field_size(&self) -> usize {
        self.field.field_size()
    }
}
impl FromFieldRepr for MerkleTreeDigest {
    const FIELD_SIZE: usize = <Fr as FromFieldRepr>::FIELD_SIZE;
    fn from_field_repr(r: &[Fr]) -> Option<Self> {
        if r.len() < Self::FIELD_SIZE { return None; }
        let mut _offset = 0usize;
        let field = <Fr as FromFieldRepr>::from_field_repr(&r[_offset.._offset + <Fr as FromFieldRepr>::FIELD_SIZE])?;
        _offset += <Fr as FromFieldRepr>::FIELD_SIZE;
        let _ = _offset;
        Some(MerkleTreeDigest { field })
    }
}
impl From<MerkleTreeDigest> for compact_runtime::Value {
    fn from(s: MerkleTreeDigest) -> compact_runtime::Value {
        let mut _v: Vec<compact_runtime::Value> = Vec::new();
        _v.push(compact_runtime::Value::from(s.field));
        compact_runtime::Value::concat(_v.iter())
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
#[repr(u8)]
pub enum PermissibleVotes {
    yes = 0,
    no = 1,
}
impl Aligned for PermissibleVotes {
    fn alignment() -> Alignment {
        u8::alignment()
    }
}
impl FieldRepr for PermissibleVotes {
    fn field_repr<W: MemWrite<Fr>>(&self, writer: &mut W) {
        (*self as u8).field_repr(writer);
    }
    fn field_size(&self) -> usize { 1 }
}
impl FromFieldRepr for PermissibleVotes {
    const FIELD_SIZE: usize = 1;
    fn from_field_repr(r: &[Fr]) -> Option<Self> {
        let n = u8::from_field_repr(r)?;
        match n {
            0 => Some(Self::yes),
            1 => Some(Self::no),
            _ => None,
        }
    }
}
impl From<PermissibleVotes> for compact_runtime::Value {
    fn from(v: PermissibleVotes) -> compact_runtime::Value {
        compact_runtime::Value::from(v as u8)
    }
}
#[derive(Clone, Debug, PartialEq, Eq, Default)]
pub struct LeafPreimage {
    pub domain_sep: [u8; 6],
    pub data: [u8; 32],
}
impl Aligned for LeafPreimage {
    fn alignment() -> Alignment {
        Alignment::concat([&<[u8; 6] as Aligned>::alignment(), &<[u8; 32] as Aligned>::alignment()])
    }
}
impl FieldRepr for LeafPreimage {
    fn field_repr<W: MemWrite<Fr>>(&self, writer: &mut W) {
        self.domain_sep.field_repr(writer);
        self.data.field_repr(writer);
    }
    fn field_size(&self) -> usize {
        self.domain_sep.field_size() + self.data.field_size()
    }
}
impl FromFieldRepr for LeafPreimage {
    const FIELD_SIZE: usize = compact_runtime::bytes_field_size(6) + <[u8; 32] as FromFieldRepr>::FIELD_SIZE;
    fn from_field_repr(r: &[Fr]) -> Option<Self> {
        if r.len() < Self::FIELD_SIZE { return None; }
        let mut _offset = 0usize;
        let domain_sep = compact_runtime::bytes_from_field_repr::<6>(&r[_offset.._offset + compact_runtime::bytes_field_size(6)])?;
        _offset += compact_runtime::bytes_field_size(6);
        let data = <[u8; 32] as FromFieldRepr>::from_field_repr(&r[_offset.._offset + <[u8; 32] as FromFieldRepr>::FIELD_SIZE])?;
        _offset += <[u8; 32] as FromFieldRepr>::FIELD_SIZE;
        let _ = _offset;
        Some(LeafPreimage { domain_sep, data })
    }
}
impl From<LeafPreimage> for compact_runtime::Value {
    fn from(s: LeafPreimage) -> compact_runtime::Value {
        let mut _v: Vec<compact_runtime::Value> = Vec::new();
        _v.push(compact_runtime::Value::from(s.domain_sep));
        _v.push(compact_runtime::Value::from(s.data));
        compact_runtime::Value::concat(_v.iter())
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
#[repr(u8)]
pub enum PrivateState {
    initial = 0,
    committed = 1,
    revealed = 2,
}
impl Aligned for PrivateState {
    fn alignment() -> Alignment {
        u8::alignment()
    }
}
impl FieldRepr for PrivateState {
    fn field_repr<W: MemWrite<Fr>>(&self, writer: &mut W) {
        (*self as u8).field_repr(writer);
    }
    fn field_size(&self) -> usize { 1 }
}
impl FromFieldRepr for PrivateState {
    const FIELD_SIZE: usize = 1;
    fn from_field_repr(r: &[Fr]) -> Option<Self> {
        let n = u8::from_field_repr(r)?;
        match n {
            0 => Some(Self::initial),
            1 => Some(Self::committed),
            2 => Some(Self::revealed),
            _ => None,
        }
    }
}
impl From<PrivateState> for compact_runtime::Value {
    fn from(v: PrivateState) -> compact_runtime::Value {
        compact_runtime::Value::from(v as u8)
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
#[repr(u8)]
pub enum PublicState {
    setup = 0,
    commit = 1,
    reveal = 2,
    r#final = 3,
}
impl Aligned for PublicState {
    fn alignment() -> Alignment {
        u8::alignment()
    }
}
impl FieldRepr for PublicState {
    fn field_repr<W: MemWrite<Fr>>(&self, writer: &mut W) {
        (*self as u8).field_repr(writer);
    }
    fn field_size(&self) -> usize { 1 }
}
impl FromFieldRepr for PublicState {
    const FIELD_SIZE: usize = 1;
    fn from_field_repr(r: &[Fr]) -> Option<Self> {
        let n = u8::from_field_repr(r)?;
        match n {
            0 => Some(Self::setup),
            1 => Some(Self::commit),
            2 => Some(Self::reveal),
            3 => Some(Self::r#final),
            _ => None,
        }
    }
}
impl From<PublicState> for compact_runtime::Value {
    fn from(v: PublicState) -> compact_runtime::Value {
        compact_runtime::Value::from(v as u8)
    }
}

pub trait Witnesses<PS> {
    fn private_secret_key<'a>(&self, ctx: &WitnessContext<Ledger<'a>, PS>) -> (PS, [u8; 32]);
    fn private_state<'a>(&self, ctx: &WitnessContext<Ledger<'a>, PS>) -> (PS, PrivateState);
    fn private_state_advance<'a>(&self, ctx: &WitnessContext<Ledger<'a>, PS>) -> (PS, ());
    fn private_vote_record<'a>(&self, ctx: &WitnessContext<Ledger<'a>, PS>, ballot: PermissibleVotes) -> (PS, ());
    fn private_vote<'a>(&self, ctx: &WitnessContext<Ledger<'a>, PS>) -> (PS, PermissibleVotes);
    fn context_eligible_voters_path_of<'a>(&self, ctx: &WitnessContext<Ledger<'a>, PS>, pk: [u8; 32]) -> (PS, Maybe<compact_runtime::MerklePath<[u8; 32]>>);
    fn context_committed_votes_path_of<'a>(&self, ctx: &WitnessContext<Ledger<'a>, PS>, cm: [u8; 32]) -> (PS, Maybe<compact_runtime::MerklePath<[u8; 32]>>);
}

pub struct Contract<PS, W = NoWitnesses>
where
    W: Witnesses<PS>,
{
    pub witnesses: W,
    _ps: PhantomData<PS>,
}

impl<PS, W> Contract<PS, W>
where
    W: Witnesses<PS>,
{
    pub fn new(witnesses: W) -> Self {
        Self { witnesses, _ps: PhantomData }
    }
    pub fn initial_state(
        &self,
        ctx: ConstructorContext<PS>,
    ) -> Result<ConstructorResult<PS>, CompactError> {
        let sv = new_array(vec![
            new_cell([0u8; 32]),
            new_cell(0u8),
            new_cell(Maybe::<compact_runtime::std_lib::OpaqueString>::default()),
            new_cell(0u64),
            new_cell(0u64),
            new_merkle_tree(10),
            new_merkle_tree(10),
            new_map(),
            new_map(),
        ]);
        let state = ChargedState::new(sv);
        let qctx = QueryContext::new(state, ContractAddress::default());
        Ok(ConstructorResult {
            current_contract_state: qctx.state,
            current_private_state: ctx.initial_private_state,
            current_zswap_local_state: ctx.empty_zswap_local_state,
        })
    }

    pub fn vote_commit(
        &self,
        ctx: CircuitContext<PS>,
        ballot: PermissibleVotes,
    ) -> Result<CircuitResults<PS, ()>, CompactError> {
        unimplemented!("M3-I3: circuit body emission for vote$commit")
    }

    pub fn vote_reveal(
        &self,
        ctx: CircuitContext<PS>,
    ) -> Result<CircuitResults<PS, ()>, CompactError> {
        unimplemented!("M3-I3: circuit body emission for vote$reveal")
    }

    pub fn advance(
        &self,
        ctx: CircuitContext<PS>,
    ) -> Result<CircuitResults<PS, ()>, CompactError> {
        let _witness_ctx_0 = WitnessContext::new(ledger(&ctx.current_query_context.state), ctx.current_private_state, &ctx.current_query_context);
        let (current_private_state, sk) = self.witnesses.private_secret_key(&_witness_ctx_0);
        let apk = pure_circuits::public_key(sk);
        compact_assert!((apk == {
            let _gather_ops = OpProgramGather::<DefaultDB>::new()
                .dup(0)
                .idx_at_index(0u8, false)
                .popeq(true)
                .build();
            let _gather_results = query_for_read(
                &ctx.current_query_context,
                &_gather_ops,
                None,
                &initial_cost_model(),
            )
            .map_err(|e| CompactError::AssertionFailed(format!("ledger query failed: {:?}", e)))?;
            let _av = match _gather_results.events.last() {
                Some(compact_runtime::onchain_vm::result_mode::GatherEvent::Read(av)) => av,
                _ => return Err(CompactError::AssertionFailed("ledger: expected Read event".into())),
            };
            compact_runtime::std_lib::decode_bytes::<32>(_av)?
        }), "Attempted to advance state without authorization");
        compact_assert!({
            let _gather_ops = OpProgramGather::<DefaultDB>::new()
                .dup(0)
                .idx_at_index(2u8, false)
                .popeq(true)
                .build();
            let _gather_results = query_for_read(
                &ctx.current_query_context,
                &_gather_ops,
                None,
                &initial_cost_model(),
            )
            .map_err(|e| CompactError::AssertionFailed(format!("ledger query failed: {:?}", e)))?;
            let _av = match _gather_results.events.last() {
                Some(compact_runtime::onchain_vm::result_mode::GatherEvent::Read(av)) => av,
                _ => return Err(CompactError::AssertionFailed("ledger: expected Read event".into())),
            };
            compact_runtime::std_lib::decode_bool(_av)?
        }, "Attempted to start election without a topic");
        let tmp = pure_circuits::successor({
            let _gather_ops = OpProgramGather::<DefaultDB>::new()
                .dup(0)
                .idx_at_index(1u8, false)
                .popeq(true)
                .build();
            let _gather_results = query_for_read(
                &ctx.current_query_context,
                &_gather_ops,
                None,
                &initial_cost_model(),
            )
            .map_err(|e| CompactError::AssertionFailed(format!("ledger query failed: {:?}", e)))?;
            let _av = match _gather_results.events.last() {
                Some(compact_runtime::onchain_vm::result_mode::GatherEvent::Read(av)) => av,
                _ => return Err(CompactError::AssertionFailed("ledger: expected Read event".into())),
            };
            compact_runtime::std_lib::decode_via_field_repr::<PublicState>(_av)?
        });
        let ops = OpProgramVerify::<DefaultDB>::new()
            .push(false, new_cell(1u8))
            .push(true, new_cell(tmp))
            .ins(false, 1)
            .build();

        let results = query_for_verify(
            &ctx.current_query_context,
            &ops,
            ctx.gas_limit.clone(),
            &ctx.cost_model,
        )?;

        Ok(CircuitResults {
            result: (),
            context: CircuitContext {
                current_query_context: results.context,
                current_private_state,
                ..ctx
            },
            gas_cost: results.gas_cost,
        })
    }

    pub fn set_topic(
        &self,
        ctx: CircuitContext<PS>,
        t: compact_runtime::std_lib::OpaqueString,
    ) -> Result<CircuitResults<PS, ()>, CompactError> {
        let _witness_ctx_0 = WitnessContext::new(ledger(&ctx.current_query_context.state), ctx.current_private_state, &ctx.current_query_context);
        let (current_private_state, sk) = self.witnesses.private_secret_key(&_witness_ctx_0);
        let apk = pure_circuits::public_key(sk);
        compact_assert!((apk == {
            let _gather_ops = OpProgramGather::<DefaultDB>::new()
                .dup(0)
                .idx_at_index(0u8, false)
                .popeq(true)
                .build();
            let _gather_results = query_for_read(
                &ctx.current_query_context,
                &_gather_ops,
                None,
                &initial_cost_model(),
            )
            .map_err(|e| CompactError::AssertionFailed(format!("ledger query failed: {:?}", e)))?;
            let _av = match _gather_results.events.last() {
                Some(compact_runtime::onchain_vm::result_mode::GatherEvent::Read(av)) => av,
                _ => return Err(CompactError::AssertionFailed("ledger: expected Read event".into())),
            };
            compact_runtime::std_lib::decode_bytes::<32>(_av)?
        }), "Attempted to set topic without authorization");
        compact_assert!(({
            let _gather_ops = OpProgramGather::<DefaultDB>::new()
                .dup(0)
                .idx_at_index(1u8, false)
                .popeq(true)
                .build();
            let _gather_results = query_for_read(
                &ctx.current_query_context,
                &_gather_ops,
                None,
                &initial_cost_model(),
            )
            .map_err(|e| CompactError::AssertionFailed(format!("ledger query failed: {:?}", e)))?;
            let _av = match _gather_results.events.last() {
                Some(compact_runtime::onchain_vm::result_mode::GatherEvent::Read(av)) => av,
                _ => return Err(CompactError::AssertionFailed("ledger: expected Read event".into())),
            };
            compact_runtime::std_lib::decode_u8(_av)?
        } == 0u8), "Attempted to set topic after setup phase");
        let tmp = Maybe { is_some: true, value: t };
        let ops = OpProgramVerify::<DefaultDB>::new()
            .push(false, new_cell(2u8))
            .push(true, new_cell(tmp))
            .ins(false, 1)
            .build();

        let results = query_for_verify(
            &ctx.current_query_context,
            &ops,
            ctx.gas_limit.clone(),
            &ctx.cost_model,
        )?;

        Ok(CircuitResults {
            result: (),
            context: CircuitContext {
                current_query_context: results.context,
                current_private_state,
                ..ctx
            },
            gas_cost: results.gas_cost,
        })
    }

    pub fn add_voter(
        &self,
        ctx: CircuitContext<PS>,
        pk: [u8; 32],
    ) -> Result<CircuitResults<PS, ()>, CompactError> {
        let _witness_ctx_h0 = WitnessContext::new(ledger(&ctx.current_query_context.state), ctx.current_private_state, &ctx.current_query_context);
        let (current_private_state, _w_context_eligible_voters_path_of_0) = self.witnesses.context_eligible_voters_path_of(&_witness_ctx_h0, pk.clone());
        compact_assert!((!(_w_context_eligible_voters_path_of_0.is_some)), "Attempted to add a voter twice");
        let _witness_ctx_3 = WitnessContext::new(ledger(&ctx.current_query_context.state), current_private_state, &ctx.current_query_context);
        let (current_private_state, sk) = self.witnesses.private_secret_key(&_witness_ctx_3);
        let apk = pure_circuits::public_key(sk);
        compact_assert!((apk == {
            let _gather_ops = OpProgramGather::<DefaultDB>::new()
                .dup(0)
                .idx_at_index(0u8, false)
                .popeq(true)
                .build();
            let _gather_results = query_for_read(
                &ctx.current_query_context,
                &_gather_ops,
                None,
                &initial_cost_model(),
            )
            .map_err(|e| CompactError::AssertionFailed(format!("ledger query failed: {:?}", e)))?;
            let _av = match _gather_results.events.last() {
                Some(compact_runtime::onchain_vm::result_mode::GatherEvent::Read(av)) => av,
                _ => return Err(CompactError::AssertionFailed("ledger: expected Read event".into())),
            };
            compact_runtime::std_lib::decode_bytes::<32>(_av)?
        }), "Attempted to add a voter without authorization");
        compact_assert!(({
            let _gather_ops = OpProgramGather::<DefaultDB>::new()
                .dup(0)
                .idx_at_index(1u8, false)
                .popeq(true)
                .build();
            let _gather_results = query_for_read(
                &ctx.current_query_context,
                &_gather_ops,
                None,
                &initial_cost_model(),
            )
            .map_err(|e| CompactError::AssertionFailed(format!("ledger query failed: {:?}", e)))?;
            let _av = match _gather_results.events.last() {
                Some(compact_runtime::onchain_vm::result_mode::GatherEvent::Read(av)) => av,
                _ => return Err(CompactError::AssertionFailed("ledger: expected Read event".into())),
            };
            compact_runtime::std_lib::decode_u8(_av)?
        } == 0u8), "Attempted to add a voter after setup phase");
        let ops = OpProgramVerify::<DefaultDB>::new()
            .idx_at_index(6u8, true)
            .idx_at_index(0u8, true)
            .dup(2)
            .idx_at_index(1u8, false)
            .push(true, new_cell(leaf_hash(&ValueReprAlignedValue(AlignedValue::from(pk)))))
            .ins(false, 1)
            .ins(true, 1)
            .idx_at_index(1u8, true)
            .addi(1)
            .ins(true, 2)
            .build();

        let results = query_for_verify(
            &ctx.current_query_context,
            &ops,
            ctx.gas_limit.clone(),
            &ctx.cost_model,
        )?;

        Ok(CircuitResults {
            result: (),
            context: CircuitContext {
                current_query_context: results.context,
                current_private_state,
                ..ctx
            },
            gas_cost: results.gas_cost,
        })
    }

}

pub struct Ledger<'a, D: DB = DefaultDB> {
    state: &'a ChargedState<D>,
}

pub fn ledger<D: DB>(state: &ChargedState<D>) -> Ledger<'_, D> {
    Ledger { state }
}

impl<'a, D: DB> Ledger<'a, D> {
}

pub mod pure_circuits {
    use super::*;

    pub(crate) fn ballot_repr(ballot: PermissibleVotes) -> [u8; 32] {
        if (ballot == PermissibleVotes::yes) {
            [121u8, 101, 115, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
        } else {
            [110u8, 111, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
        }
    }

    pub(crate) fn successor(state: PublicState) -> PublicState {
        if (state == PublicState::setup) {
            PublicState::commit
        } else {
            if (state == PublicState::commit) {
            PublicState::reveal
        } else {
            PublicState::r#final
        }
        }
    }

    pub(crate) fn commitment_nullifier(sk: [u8; 32]) -> [u8; 32] {
        compact_runtime::std_lib::persistent_hash_aligned(&[compact_runtime::AlignedValue::from([108u8, 97, 114, 101, 115, 58, 101, 108, 101, 99, 116, 105, 111, 110, 58, 99, 109, 45, 110, 117, 108, 58, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), compact_runtime::AlignedValue::from(sk)])
    }

    pub(crate) fn reveal_nullifier(sk: [u8; 32]) -> [u8; 32] {
        compact_runtime::std_lib::persistent_hash_aligned(&[compact_runtime::AlignedValue::from([108u8, 97, 114, 101, 115, 58, 101, 108, 101, 99, 116, 105, 111, 110, 58, 114, 118, 45, 110, 117, 108, 58, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), compact_runtime::AlignedValue::from(sk)])
    }

    pub(crate) fn public_key(sk: [u8; 32]) -> [u8; 32] {
        compact_runtime::std_lib::persistent_hash_aligned(&[compact_runtime::AlignedValue::from([108u8, 97, 114, 101, 115, 58, 101, 108, 101, 99, 116, 105, 111, 110, 58, 112, 107, 58, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), compact_runtime::AlignedValue::from(sk)])
    }

    pub(crate) fn commit_with_sk(ballot: [u8; 32], sk: [u8; 32]) -> [u8; 32] {
        compact_runtime::std_lib::persistent_hash_aligned(&[compact_runtime::AlignedValue::from(ballot), compact_runtime::AlignedValue::from(sk)])
    }

}
