import inspect from 'object-inspect';

/**
 * An error originating from code generated by the Compact compiler
 */
export class CompactError extends Error {
  constructor(msg: string) {
    super(msg);
    this.name = 'CompactError';
  }
}

/**
 * Compiler internal for assertions
 * @internal
 */
export function assert(b: boolean, s: string): void {
  if (!b) {
    const msg = `failed assert: ${s}`;
    throw new CompactError(msg);
  }
}

/**
 * Compiler internal for asserting an object is non-nullable.
 * @internal
 */
export function assertDefined<T>(t: T | undefined, name: string): asserts t is NonNullable<T> {
  if (t === undefined || t === null) {
    throw new CompactError(`Expected ${name} to be defined`);
  }
}

/**
 * Compiler internal for type errors
 * @internal
 */
export function typeError(who: string, what: string, where: string, type: string, x: unknown): never {
  const msg = `type error: ${who} ${what} at ${where}; expected value of type ${type} but received ${inspect(x)}`;
  throw new CompactError(msg);
}
