// SPDX-License-Identifier: Apache-2.0
// Generated by compactc. Do not edit by hand.

#![allow(clippy::all, dead_code, unused_imports, unused_variables)]

use compact_runtime::*;
use std::marker::PhantomData;

compact_runtime::check_runtime_version!("0.16.100");

#[derive(Clone, Debug, PartialEq, Eq, Default)]
pub struct commitment {
    pub bytes: [u8; 32],
}
impl Aligned for commitment {
    fn alignment() -> Alignment {
        Alignment::concat([&<[u8; 32] as Aligned>::alignment()])
    }
}
impl FieldRepr for commitment {
    fn field_repr<W: MemWrite<Fr>>(&self, writer: &mut W) {
        self.bytes.field_repr(writer);
    }
    fn field_size(&self) -> usize {
        self.bytes.field_size()
    }
}
impl FromFieldRepr for commitment {
    const FIELD_SIZE: usize = <[u8; 32] as FromFieldRepr>::FIELD_SIZE;
    fn from_field_repr(r: &[Fr]) -> Option<Self> {
        if r.len() < Self::FIELD_SIZE { return None; }
        let mut _offset = 0usize;
        let bytes = <[u8; 32] as FromFieldRepr>::from_field_repr(&r[_offset.._offset + <[u8; 32] as FromFieldRepr>::FIELD_SIZE])?;
        _offset += <[u8; 32] as FromFieldRepr>::FIELD_SIZE;
        let _ = _offset;
        Some(commitment { bytes })
    }
}
impl From<commitment> for compact_runtime::Value {
    fn from(s: commitment) -> compact_runtime::Value {
        let mut _v: Vec<compact_runtime::Value> = Vec::new();
        _v.push(compact_runtime::Value::from(s.bytes));
        compact_runtime::Value::concat(_v.iter())
    }
}

#[derive(Clone, Debug, PartialEq, Eq, Default)]
pub struct coin_info {
    pub nonce: Nonce,
    pub opening: opening,
}
impl Aligned for coin_info {
    fn alignment() -> Alignment {
        Alignment::concat([&<Nonce as Aligned>::alignment(), &<opening as Aligned>::alignment()])
    }
}
impl FieldRepr for coin_info {
    fn field_repr<W: MemWrite<Fr>>(&self, writer: &mut W) {
        self.nonce.field_repr(writer);
        self.opening.field_repr(writer);
    }
    fn field_size(&self) -> usize {
        self.nonce.field_size() + self.opening.field_size()
    }
}
impl FromFieldRepr for coin_info {
    const FIELD_SIZE: usize = <Nonce as FromFieldRepr>::FIELD_SIZE + <opening as FromFieldRepr>::FIELD_SIZE;
    fn from_field_repr(r: &[Fr]) -> Option<Self> {
        if r.len() < Self::FIELD_SIZE { return None; }
        let mut _offset = 0usize;
        let nonce = <Nonce as FromFieldRepr>::from_field_repr(&r[_offset.._offset + <Nonce as FromFieldRepr>::FIELD_SIZE])?;
        _offset += <Nonce as FromFieldRepr>::FIELD_SIZE;
        let opening = <opening as FromFieldRepr>::from_field_repr(&r[_offset.._offset + <opening as FromFieldRepr>::FIELD_SIZE])?;
        _offset += <opening as FromFieldRepr>::FIELD_SIZE;
        let _ = _offset;
        Some(coin_info { nonce, opening })
    }
}
impl From<coin_info> for compact_runtime::Value {
    fn from(s: coin_info) -> compact_runtime::Value {
        let mut _v: Vec<compact_runtime::Value> = Vec::new();
        _v.push(compact_runtime::Value::from(s.nonce));
        _v.push(compact_runtime::Value::from(s.opening));
        compact_runtime::Value::concat(_v.iter())
    }
}

#[derive(Clone, Debug, PartialEq, Eq, Default)]
pub struct LeafPreimage {
    pub domain_sep: [u8; 6],
    pub data: commitment,
}
impl Aligned for LeafPreimage {
    fn alignment() -> Alignment {
        Alignment::concat([&<[u8; 6] as Aligned>::alignment(), &<commitment as Aligned>::alignment()])
    }
}
impl FieldRepr for LeafPreimage {
    fn field_repr<W: MemWrite<Fr>>(&self, writer: &mut W) {
        self.domain_sep.field_repr(writer);
        self.data.field_repr(writer);
    }
    fn field_size(&self) -> usize {
        self.domain_sep.field_size() + self.data.field_size()
    }
}
impl FromFieldRepr for LeafPreimage {
    const FIELD_SIZE: usize = compact_runtime::bytes_field_size(6) + <commitment as FromFieldRepr>::FIELD_SIZE;
    fn from_field_repr(r: &[Fr]) -> Option<Self> {
        if r.len() < Self::FIELD_SIZE { return None; }
        let mut _offset = 0usize;
        let domain_sep = compact_runtime::bytes_from_field_repr::<6>(&r[_offset.._offset + compact_runtime::bytes_field_size(6)])?;
        _offset += compact_runtime::bytes_field_size(6);
        let data = <commitment as FromFieldRepr>::from_field_repr(&r[_offset.._offset + <commitment as FromFieldRepr>::FIELD_SIZE])?;
        _offset += <commitment as FromFieldRepr>::FIELD_SIZE;
        let _ = _offset;
        Some(LeafPreimage { domain_sep, data })
    }
}
impl From<LeafPreimage> for compact_runtime::Value {
    fn from(s: LeafPreimage) -> compact_runtime::Value {
        let mut _v: Vec<compact_runtime::Value> = Vec::new();
        _v.push(compact_runtime::Value::from(s.domain_sep));
        _v.push(compact_runtime::Value::from(s.data));
        compact_runtime::Value::concat(_v.iter())
    }
}

#[derive(Clone, Debug, PartialEq, Eq, Default)]
pub struct public_key {
    pub zk: zk_public_key,
    pub encryption: Vec<u8>,
}
impl Aligned for public_key {
    fn alignment() -> Alignment {
        Alignment::concat([&<zk_public_key as Aligned>::alignment(), &<Vec<u8> as Aligned>::alignment()])
    }
}
impl FieldRepr for public_key {
    fn field_repr<W: MemWrite<Fr>>(&self, writer: &mut W) {
        self.zk.field_repr(writer);
        self.encryption.field_repr(writer);
    }
    fn field_size(&self) -> usize {
        self.zk.field_size() + self.encryption.field_size()
    }
}
impl FromFieldRepr for public_key {
    const FIELD_SIZE: usize = <zk_public_key as FromFieldRepr>::FIELD_SIZE + 0;
    fn from_field_repr(r: &[Fr]) -> Option<Self> {
        if r.len() < Self::FIELD_SIZE { return None; }
        let mut _offset = 0usize;
        let zk = <zk_public_key as FromFieldRepr>::from_field_repr(&r[_offset.._offset + <zk_public_key as FromFieldRepr>::FIELD_SIZE])?;
        _offset += <zk_public_key as FromFieldRepr>::FIELD_SIZE;
        let encryption = compact_runtime::vec_u8_from_field_repr(&r[_offset.._offset])?;
        let _ = _offset;
        Some(public_key { zk, encryption })
    }
}
impl From<public_key> for compact_runtime::Value {
    fn from(s: public_key) -> compact_runtime::Value {
        let mut _v: Vec<compact_runtime::Value> = Vec::new();
        _v.push(compact_runtime::Value::from(s.zk));
        _v.push(compact_runtime::Value::from(s.encryption));
        compact_runtime::Value::concat(_v.iter())
    }
}

#[derive(Clone, Debug, PartialEq, Eq, Default)]
pub struct Nonce {
    pub bytes: [u8; 32],
}
impl Aligned for Nonce {
    fn alignment() -> Alignment {
        Alignment::concat([&<[u8; 32] as Aligned>::alignment()])
    }
}
impl FieldRepr for Nonce {
    fn field_repr<W: MemWrite<Fr>>(&self, writer: &mut W) {
        self.bytes.field_repr(writer);
    }
    fn field_size(&self) -> usize {
        self.bytes.field_size()
    }
}
impl FromFieldRepr for Nonce {
    const FIELD_SIZE: usize = <[u8; 32] as FromFieldRepr>::FIELD_SIZE;
    fn from_field_repr(r: &[Fr]) -> Option<Self> {
        if r.len() < Self::FIELD_SIZE { return None; }
        let mut _offset = 0usize;
        let bytes = <[u8; 32] as FromFieldRepr>::from_field_repr(&r[_offset.._offset + <[u8; 32] as FromFieldRepr>::FIELD_SIZE])?;
        _offset += <[u8; 32] as FromFieldRepr>::FIELD_SIZE;
        let _ = _offset;
        Some(Nonce { bytes })
    }
}
impl From<Nonce> for compact_runtime::Value {
    fn from(s: Nonce) -> compact_runtime::Value {
        let mut _v: Vec<compact_runtime::Value> = Vec::new();
        _v.push(compact_runtime::Value::from(s.bytes));
        compact_runtime::Value::concat(_v.iter())
    }
}

#[derive(Clone, Debug, PartialEq, Eq, Default)]
pub struct MerkleTreeDigest {
    pub field: Fr,
}
impl Aligned for MerkleTreeDigest {
    fn alignment() -> Alignment {
        Alignment::concat([&<Fr as Aligned>::alignment()])
    }
}
impl FieldRepr for MerkleTreeDigest {
    fn field_repr<W: MemWrite<Fr>>(&self, writer: &mut W) {
        self.field.field_repr(writer);
    }
    fn field_size(&self) -> usize {
        self.field.field_size()
    }
}
impl FromFieldRepr for MerkleTreeDigest {
    const FIELD_SIZE: usize = <Fr as FromFieldRepr>::FIELD_SIZE;
    fn from_field_repr(r: &[Fr]) -> Option<Self> {
        if r.len() < Self::FIELD_SIZE { return None; }
        let mut _offset = 0usize;
        let field = <Fr as FromFieldRepr>::from_field_repr(&r[_offset.._offset + <Fr as FromFieldRepr>::FIELD_SIZE])?;
        _offset += <Fr as FromFieldRepr>::FIELD_SIZE;
        let _ = _offset;
        Some(MerkleTreeDigest { field })
    }
}
impl From<MerkleTreeDigest> for compact_runtime::Value {
    fn from(s: MerkleTreeDigest) -> compact_runtime::Value {
        let mut _v: Vec<compact_runtime::Value> = Vec::new();
        _v.push(compact_runtime::Value::from(s.field));
        compact_runtime::Value::concat(_v.iter())
    }
}

#[derive(Clone, Debug, PartialEq, Eq, Default)]
pub struct zk_secret_key {
    pub bytes: [u8; 32],
}
impl Aligned for zk_secret_key {
    fn alignment() -> Alignment {
        Alignment::concat([&<[u8; 32] as Aligned>::alignment()])
    }
}
impl FieldRepr for zk_secret_key {
    fn field_repr<W: MemWrite<Fr>>(&self, writer: &mut W) {
        self.bytes.field_repr(writer);
    }
    fn field_size(&self) -> usize {
        self.bytes.field_size()
    }
}
impl FromFieldRepr for zk_secret_key {
    const FIELD_SIZE: usize = <[u8; 32] as FromFieldRepr>::FIELD_SIZE;
    fn from_field_repr(r: &[Fr]) -> Option<Self> {
        if r.len() < Self::FIELD_SIZE { return None; }
        let mut _offset = 0usize;
        let bytes = <[u8; 32] as FromFieldRepr>::from_field_repr(&r[_offset.._offset + <[u8; 32] as FromFieldRepr>::FIELD_SIZE])?;
        _offset += <[u8; 32] as FromFieldRepr>::FIELD_SIZE;
        let _ = _offset;
        Some(zk_secret_key { bytes })
    }
}
impl From<zk_secret_key> for compact_runtime::Value {
    fn from(s: zk_secret_key) -> compact_runtime::Value {
        let mut _v: Vec<compact_runtime::Value> = Vec::new();
        _v.push(compact_runtime::Value::from(s.bytes));
        compact_runtime::Value::concat(_v.iter())
    }
}

#[derive(Clone, Debug, PartialEq, Eq, Default)]
pub struct zk_public_key {
    pub bytes: [u8; 32],
}
impl Aligned for zk_public_key {
    fn alignment() -> Alignment {
        Alignment::concat([&<[u8; 32] as Aligned>::alignment()])
    }
}
impl FieldRepr for zk_public_key {
    fn field_repr<W: MemWrite<Fr>>(&self, writer: &mut W) {
        self.bytes.field_repr(writer);
    }
    fn field_size(&self) -> usize {
        self.bytes.field_size()
    }
}
impl FromFieldRepr for zk_public_key {
    const FIELD_SIZE: usize = <[u8; 32] as FromFieldRepr>::FIELD_SIZE;
    fn from_field_repr(r: &[Fr]) -> Option<Self> {
        if r.len() < Self::FIELD_SIZE { return None; }
        let mut _offset = 0usize;
        let bytes = <[u8; 32] as FromFieldRepr>::from_field_repr(&r[_offset.._offset + <[u8; 32] as FromFieldRepr>::FIELD_SIZE])?;
        _offset += <[u8; 32] as FromFieldRepr>::FIELD_SIZE;
        let _ = _offset;
        Some(zk_public_key { bytes })
    }
}
impl From<zk_public_key> for compact_runtime::Value {
    fn from(s: zk_public_key) -> compact_runtime::Value {
        let mut _v: Vec<compact_runtime::Value> = Vec::new();
        _v.push(compact_runtime::Value::from(s.bytes));
        compact_runtime::Value::concat(_v.iter())
    }
}

#[derive(Clone, Debug, PartialEq, Eq, Default)]
pub struct opening {
    pub bytes: [u8; 32],
}
impl Aligned for opening {
    fn alignment() -> Alignment {
        Alignment::concat([&<[u8; 32] as Aligned>::alignment()])
    }
}
impl FieldRepr for opening {
    fn field_repr<W: MemWrite<Fr>>(&self, writer: &mut W) {
        self.bytes.field_repr(writer);
    }
    fn field_size(&self) -> usize {
        self.bytes.field_size()
    }
}
impl FromFieldRepr for opening {
    const FIELD_SIZE: usize = <[u8; 32] as FromFieldRepr>::FIELD_SIZE;
    fn from_field_repr(r: &[Fr]) -> Option<Self> {
        if r.len() < Self::FIELD_SIZE { return None; }
        let mut _offset = 0usize;
        let bytes = <[u8; 32] as FromFieldRepr>::from_field_repr(&r[_offset.._offset + <[u8; 32] as FromFieldRepr>::FIELD_SIZE])?;
        _offset += <[u8; 32] as FromFieldRepr>::FIELD_SIZE;
        let _ = _offset;
        Some(opening { bytes })
    }
}
impl From<opening> for compact_runtime::Value {
    fn from(s: opening) -> compact_runtime::Value {
        let mut _v: Vec<compact_runtime::Value> = Vec::new();
        _v.push(compact_runtime::Value::from(s.bytes));
        compact_runtime::Value::concat(_v.iter())
    }
}

#[derive(Clone, Debug, PartialEq, Eq, Default)]
pub struct nullifier {
    pub bytes: [u8; 32],
}
impl Aligned for nullifier {
    fn alignment() -> Alignment {
        Alignment::concat([&<[u8; 32] as Aligned>::alignment()])
    }
}
impl FieldRepr for nullifier {
    fn field_repr<W: MemWrite<Fr>>(&self, writer: &mut W) {
        self.bytes.field_repr(writer);
    }
    fn field_size(&self) -> usize {
        self.bytes.field_size()
    }
}
impl FromFieldRepr for nullifier {
    const FIELD_SIZE: usize = <[u8; 32] as FromFieldRepr>::FIELD_SIZE;
    fn from_field_repr(r: &[Fr]) -> Option<Self> {
        if r.len() < Self::FIELD_SIZE { return None; }
        let mut _offset = 0usize;
        let bytes = <[u8; 32] as FromFieldRepr>::from_field_repr(&r[_offset.._offset + <[u8; 32] as FromFieldRepr>::FIELD_SIZE])?;
        _offset += <[u8; 32] as FromFieldRepr>::FIELD_SIZE;
        let _ = _offset;
        Some(nullifier { bytes })
    }
}
impl From<nullifier> for compact_runtime::Value {
    fn from(s: nullifier) -> compact_runtime::Value {
        let mut _v: Vec<compact_runtime::Value> = Vec::new();
        _v.push(compact_runtime::Value::from(s.bytes));
        compact_runtime::Value::concat(_v.iter())
    }
}


pub trait Witnesses<PS> {
    fn private_zk_secret_key<'a>(&self, ctx: &WitnessContext<Ledger<'a>, PS>) -> (PS, zk_secret_key);
    fn private_remove_coin<'a>(&self, ctx: &WitnessContext<Ledger<'a>, PS>, coin: coin_info) -> (PS, ());
    fn private_zk_public_key<'a>(&self, ctx: &WitnessContext<Ledger<'a>, PS>) -> (PS, zk_public_key);
    fn private_add_coin<'a>(&self, ctx: &WitnessContext<Ledger<'a>, PS>, coin: coin_info) -> (PS, ());
    fn context_path_of<'a>(&self, ctx: &WitnessContext<Ledger<'a>, PS>, cm: commitment) -> (PS, compact_runtime::MerklePath<commitment>);
    fn context_new_coin_info<'a>(&self, ctx: &WitnessContext<Ledger<'a>, PS>) -> (PS, coin_info);
    fn context_encrypt<'a>(&self, ctx: &WitnessContext<Ledger<'a>, PS>, pk: Vec<u8>, coin: coin_info) -> (PS, Vec<u8>);
}

pub struct Contract<PS, W = NoWitnesses>
where
    W: Witnesses<PS>,
{
    pub witnesses: W,
    _ps: PhantomData<PS>,
}

impl<PS, W> Contract<PS, W>
where
    W: Witnesses<PS>,
{
    pub fn new(witnesses: W) -> Self {
        Self { witnesses, _ps: PhantomData }
    }
    pub fn initial_state(
        &self,
        ctx: ConstructorContext<PS>,
    ) -> Result<ConstructorResult<PS>, CompactError> {
        let sv = new_array(vec![
            new_map(),
            new_historic_merkle_tree(32),
            new_cell(Vec::<u8>::new()),
        ]);
        let state = ChargedState::new(sv);
        let qctx = QueryContext::new(state, ContractAddress::default());
        Ok(ConstructorResult {
            current_contract_state: qctx.state,
            current_private_state: ctx.initial_private_state,
            current_zswap_local_state: ctx.empty_zswap_local_state,
        })
    }

    pub fn spend(
        &self,
        ctx: CircuitContext<PS>,
        dest_public_key: public_key,
        input_coin: coin_info,
    ) -> Result<CircuitResults<PS, ()>, CompactError> {
        unimplemented!("M3-I3: circuit body emission for spend")
    }

    pub fn zerocash_mint(
        &self,
        ctx: CircuitContext<PS>,
    ) -> Result<CircuitResults<PS, ()>, CompactError> {
        let _witness_ctx_0 = WitnessContext::new(ledger(&ctx.current_query_context.state), ctx.current_private_state, &ctx.current_query_context);
        let (current_private_state, coin) = self.witnesses.context_new_coin_info(&_witness_ctx_0);
        let _witness_ctx_2 = WitnessContext::new(ledger(&ctx.current_query_context.state), current_private_state, &ctx.current_query_context);
        let (current_private_state, pk) = self.witnesses.private_zk_public_key(&_witness_ctx_2);
        let _witness_ctx_4 = WitnessContext::new(ledger(&ctx.current_query_context.state), current_private_state, &ctx.current_query_context);
        let (current_private_state, _) = self.witnesses.private_add_coin(&_witness_ctx_4, coin.clone());
        let cm = pure_circuits::commitment_from_coin_info(coin, pk);
        let ops = OpProgramVerify::<DefaultDB>::new()
            .idx_at_index(1u8, true)
            .idx_at_index(0u8, true)
            .dup(2)
            .idx_at_index(1u8, false)
            .push(true, new_cell(leaf_hash(&ValueReprAlignedValue(AlignedValue::from(cm)))))
            .ins(false, 1)
            .ins(true, 1)
            .idx_at_index(1u8, true)
            .addi(1)
            .ins(true, 1)
            .idx_at_index(2u8, true)
            .dup(2)
            .idx_at_index(0u8, false)
            .root()
            .push(true, StateValue::Null)
            .ins(false, 1)
            .ins(true, 2)
            .build();

        let results = query_for_verify(
            &ctx.current_query_context,
            &ops,
            ctx.gas_limit.clone(),
            &ctx.cost_model,
        )?;

        Ok(CircuitResults {
            result: (),
            context: CircuitContext {
                current_query_context: results.context,
                current_private_state,
                ..ctx
            },
            gas_cost: results.gas_cost,
        })
    }

}

pub struct Ledger<'a, D: DB = DefaultDB> {
    state: &'a ChargedState<D>,
}

pub fn ledger<D: DB>(state: &ChargedState<D>) -> Ledger<'_, D> {
    Ledger { state }
}

impl<'a, D: DB> Ledger<'a, D> {
}

pub mod pure_circuits {
    use super::*;

    pub(crate) fn derive_nullifier(coin: coin_info, sk: zk_secret_key) -> nullifier {
        nullifier { bytes: compact_runtime::std_lib::persistent_hash_aligned(&[compact_runtime::AlignedValue::from([108u8, 97, 114, 101, 115, 58, 122, 101, 114, 111, 99, 97, 115, 104, 58, 99, 111, 109, 109, 105, 116, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), compact_runtime::AlignedValue::from(coin.nonce.bytes), compact_runtime::AlignedValue::from(coin.opening.bytes), compact_runtime::AlignedValue::from(sk.bytes)]) }
    }

    pub(crate) fn derive_zk_public_key(sk: zk_secret_key) -> zk_public_key {
        zk_public_key { bytes: compact_runtime::std_lib::persistent_hash_aligned(&[compact_runtime::AlignedValue::from(sk.bytes)]) }
    }

    pub(crate) fn commitment_from_coin_info(coin: coin_info, pk: zk_public_key) -> commitment {
        commitment { bytes: compact_runtime::std_lib::persistent_hash_aligned(&[compact_runtime::AlignedValue::from([108u8, 97, 114, 101, 115, 58, 122, 101, 114, 111, 99, 97, 115, 104, 58, 99, 111, 109, 109, 105, 116, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), compact_runtime::AlignedValue::from(coin.nonce.bytes), compact_runtime::AlignedValue::from(coin.opening.bytes), compact_runtime::AlignedValue::from(pk.bytes)]) }
    }

}
