// SPDX-License-Identifier: Apache-2.0
// Generated by compactc. Do not edit by hand.

#![allow(clippy::all, dead_code, unused_imports, unused_variables)]

use compact_runtime::*;
use std::marker::PhantomData;

compact_runtime::check_runtime_version!("0.16.100");

#[derive(Clone, Debug, PartialEq, Eq, Default)]
pub struct commitment {
    pub bytes: [u8; 32],
}
impl Aligned for commitment {
    fn alignment() -> Alignment {
        Alignment::concat([&<[u8; 32] as Aligned>::alignment()])
    }
}
impl FieldRepr for commitment {
    fn field_repr<W: MemWrite<Fr>>(&self, writer: &mut W) {
        self.bytes.field_repr(writer);
    }
    fn field_size(&self) -> usize {
        self.bytes.field_size()
    }
}
impl FromFieldRepr for commitment {
    const FIELD_SIZE: usize = <[u8; 32] as FromFieldRepr>::FIELD_SIZE;
    fn from_field_repr(r: &[Fr]) -> Option<Self> {
        if r.len() < Self::FIELD_SIZE { return None; }
        let mut _offset = 0usize;
        let bytes = <[u8; 32] as FromFieldRepr>::from_field_repr(&r[_offset.._offset + <[u8; 32] as FromFieldRepr>::FIELD_SIZE])?;
        _offset += <[u8; 32] as FromFieldRepr>::FIELD_SIZE;
        let _ = _offset;
        Some(commitment { bytes })
    }
}

#[derive(Clone, Debug, PartialEq, Eq, Default)]
pub struct coin_info {
    pub nonce: Nonce,
    pub opening: opening,
}
impl Aligned for coin_info {
    fn alignment() -> Alignment {
        Alignment::concat([&<Nonce as Aligned>::alignment(), &<opening as Aligned>::alignment()])
    }
}
impl FieldRepr for coin_info {
    fn field_repr<W: MemWrite<Fr>>(&self, writer: &mut W) {
        self.nonce.field_repr(writer);
        self.opening.field_repr(writer);
    }
    fn field_size(&self) -> usize {
        self.nonce.field_size() + self.opening.field_size()
    }
}
impl FromFieldRepr for coin_info {
    const FIELD_SIZE: usize = <Nonce as FromFieldRepr>::FIELD_SIZE + <opening as FromFieldRepr>::FIELD_SIZE;
    fn from_field_repr(r: &[Fr]) -> Option<Self> {
        if r.len() < Self::FIELD_SIZE { return None; }
        let mut _offset = 0usize;
        let nonce = <Nonce as FromFieldRepr>::from_field_repr(&r[_offset.._offset + <Nonce as FromFieldRepr>::FIELD_SIZE])?;
        _offset += <Nonce as FromFieldRepr>::FIELD_SIZE;
        let opening = <opening as FromFieldRepr>::from_field_repr(&r[_offset.._offset + <opening as FromFieldRepr>::FIELD_SIZE])?;
        _offset += <opening as FromFieldRepr>::FIELD_SIZE;
        let _ = _offset;
        Some(coin_info { nonce, opening })
    }
}

#[derive(Clone, Debug, PartialEq, Eq, Default)]
pub struct LeafPreimage {
    pub domain_sep: [u8; 6],
    pub data: commitment,
}
impl Aligned for LeafPreimage {
    fn alignment() -> Alignment {
        Alignment::concat([&<[u8; 6] as Aligned>::alignment(), &<commitment as Aligned>::alignment()])
    }
}
impl FieldRepr for LeafPreimage {
    fn field_repr<W: MemWrite<Fr>>(&self, writer: &mut W) {
        self.domain_sep.field_repr(writer);
        self.data.field_repr(writer);
    }
    fn field_size(&self) -> usize {
        self.domain_sep.field_size() + self.data.field_size()
    }
}
impl FromFieldRepr for LeafPreimage {
    const FIELD_SIZE: usize = compact_runtime::bytes_field_size(6) + <commitment as FromFieldRepr>::FIELD_SIZE;
    fn from_field_repr(r: &[Fr]) -> Option<Self> {
        if r.len() < Self::FIELD_SIZE { return None; }
        let mut _offset = 0usize;
        let domain_sep = compact_runtime::bytes_from_field_repr::<6>(&r[_offset.._offset + compact_runtime::bytes_field_size(6)])?;
        _offset += compact_runtime::bytes_field_size(6);
        let data = <commitment as FromFieldRepr>::from_field_repr(&r[_offset.._offset + <commitment as FromFieldRepr>::FIELD_SIZE])?;
        _offset += <commitment as FromFieldRepr>::FIELD_SIZE;
        let _ = _offset;
        Some(LeafPreimage { domain_sep, data })
    }
}

#[derive(Clone, Debug, PartialEq, Eq, Default)]
pub struct MerkleTreePath {
    pub leaf: commitment,
    pub path: [MerkleTreePathEntry; 32],
}
impl Aligned for MerkleTreePath {
    fn alignment() -> Alignment {
        Alignment::concat([&<commitment as Aligned>::alignment(), &<MerkleTreePathEntry as Aligned>::alignment(), &<MerkleTreePathEntry as Aligned>::alignment(), &<MerkleTreePathEntry as Aligned>::alignment(), &<MerkleTreePathEntry as Aligned>::alignment(), &<MerkleTreePathEntry as Aligned>::alignment(), &<MerkleTreePathEntry as Aligned>::alignment(), &<MerkleTreePathEntry as Aligned>::alignment(), &<MerkleTreePathEntry as Aligned>::alignment(), &<MerkleTreePathEntry as Aligned>::alignment(), &<MerkleTreePathEntry as Aligned>::alignment(), &<MerkleTreePathEntry as Aligned>::alignment(), &<MerkleTreePathEntry as Aligned>::alignment(), &<MerkleTreePathEntry as Aligned>::alignment(), &<MerkleTreePathEntry as Aligned>::alignment(), &<MerkleTreePathEntry as Aligned>::alignment(), &<MerkleTreePathEntry as Aligned>::alignment(), &<MerkleTreePathEntry as Aligned>::alignment(), &<MerkleTreePathEntry as Aligned>::alignment(), &<MerkleTreePathEntry as Aligned>::alignment(), &<MerkleTreePathEntry as Aligned>::alignment(), &<MerkleTreePathEntry as Aligned>::alignment(), &<MerkleTreePathEntry as Aligned>::alignment(), &<MerkleTreePathEntry as Aligned>::alignment(), &<MerkleTreePathEntry as Aligned>::alignment(), &<MerkleTreePathEntry as Aligned>::alignment(), &<MerkleTreePathEntry as Aligned>::alignment(), &<MerkleTreePathEntry as Aligned>::alignment(), &<MerkleTreePathEntry as Aligned>::alignment(), &<MerkleTreePathEntry as Aligned>::alignment(), &<MerkleTreePathEntry as Aligned>::alignment(), &<MerkleTreePathEntry as Aligned>::alignment(), &<MerkleTreePathEntry as Aligned>::alignment()])
    }
}
impl FieldRepr for MerkleTreePath {
    fn field_repr<W: MemWrite<Fr>>(&self, writer: &mut W) {
        self.leaf.field_repr(writer);
        for _e in self.path.iter() { _e.field_repr(writer); }
    }
    fn field_size(&self) -> usize {
        self.leaf.field_size() + self.path.iter().map(|e| e.field_size()).sum::<usize>()
    }
}
impl FromFieldRepr for MerkleTreePath {
    const FIELD_SIZE: usize = <commitment as FromFieldRepr>::FIELD_SIZE + <MerkleTreePathEntry as FromFieldRepr>::FIELD_SIZE * 32;
    fn from_field_repr(r: &[Fr]) -> Option<Self> {
        if r.len() < Self::FIELD_SIZE { return None; }
        let mut _offset = 0usize;
        let leaf = <commitment as FromFieldRepr>::from_field_repr(&r[_offset.._offset + <commitment as FromFieldRepr>::FIELD_SIZE])?;
        _offset += <commitment as FromFieldRepr>::FIELD_SIZE;
        let path = compact_runtime::array_from_field_repr::<MerkleTreePathEntry, 32>(&r[_offset.._offset + <MerkleTreePathEntry as FromFieldRepr>::FIELD_SIZE * 32], <MerkleTreePathEntry as FromFieldRepr>::FIELD_SIZE)?;
        _offset += <MerkleTreePathEntry as FromFieldRepr>::FIELD_SIZE * 32;
        let _ = _offset;
        Some(MerkleTreePath { leaf, path })
    }
}

#[derive(Clone, Debug, PartialEq, Eq, Default)]
pub struct MerkleTreePathEntry {
    pub sibling: MerkleTreeDigest,
    pub goes_left: bool,
}
impl Aligned for MerkleTreePathEntry {
    fn alignment() -> Alignment {
        Alignment::concat([&<MerkleTreeDigest as Aligned>::alignment(), &<bool as Aligned>::alignment()])
    }
}
impl FieldRepr for MerkleTreePathEntry {
    fn field_repr<W: MemWrite<Fr>>(&self, writer: &mut W) {
        self.sibling.field_repr(writer);
        self.goes_left.field_repr(writer);
    }
    fn field_size(&self) -> usize {
        self.sibling.field_size() + self.goes_left.field_size()
    }
}
impl FromFieldRepr for MerkleTreePathEntry {
    const FIELD_SIZE: usize = <MerkleTreeDigest as FromFieldRepr>::FIELD_SIZE + <bool as FromFieldRepr>::FIELD_SIZE;
    fn from_field_repr(r: &[Fr]) -> Option<Self> {
        if r.len() < Self::FIELD_SIZE { return None; }
        let mut _offset = 0usize;
        let sibling = <MerkleTreeDigest as FromFieldRepr>::from_field_repr(&r[_offset.._offset + <MerkleTreeDigest as FromFieldRepr>::FIELD_SIZE])?;
        _offset += <MerkleTreeDigest as FromFieldRepr>::FIELD_SIZE;
        let goes_left = <bool as FromFieldRepr>::from_field_repr(&r[_offset.._offset + <bool as FromFieldRepr>::FIELD_SIZE])?;
        _offset += <bool as FromFieldRepr>::FIELD_SIZE;
        let _ = _offset;
        Some(MerkleTreePathEntry { sibling, goes_left })
    }
}

#[derive(Clone, Debug, PartialEq, Eq, Default)]
pub struct public_key {
    pub zk: zk_public_key,
    pub encryption: Vec<u8>,
}
impl Aligned for public_key {
    fn alignment() -> Alignment {
        Alignment::concat([&<zk_public_key as Aligned>::alignment(), &<Vec<u8> as Aligned>::alignment()])
    }
}
impl FieldRepr for public_key {
    fn field_repr<W: MemWrite<Fr>>(&self, writer: &mut W) {
        self.zk.field_repr(writer);
        self.encryption.field_repr(writer);
    }
    fn field_size(&self) -> usize {
        self.zk.field_size() + self.encryption.field_size()
    }
}
impl FromFieldRepr for public_key {
    const FIELD_SIZE: usize = <zk_public_key as FromFieldRepr>::FIELD_SIZE + 0;
    fn from_field_repr(r: &[Fr]) -> Option<Self> {
        if r.len() < Self::FIELD_SIZE { return None; }
        let mut _offset = 0usize;
        let zk = <zk_public_key as FromFieldRepr>::from_field_repr(&r[_offset.._offset + <zk_public_key as FromFieldRepr>::FIELD_SIZE])?;
        _offset += <zk_public_key as FromFieldRepr>::FIELD_SIZE;
        let encryption = compact_runtime::vec_u8_from_field_repr(&r[_offset.._offset])?;
        let _ = _offset;
        Some(public_key { zk, encryption })
    }
}

#[derive(Clone, Debug, PartialEq, Eq, Default)]
pub struct Nonce {
    pub bytes: [u8; 32],
}
impl Aligned for Nonce {
    fn alignment() -> Alignment {
        Alignment::concat([&<[u8; 32] as Aligned>::alignment()])
    }
}
impl FieldRepr for Nonce {
    fn field_repr<W: MemWrite<Fr>>(&self, writer: &mut W) {
        self.bytes.field_repr(writer);
    }
    fn field_size(&self) -> usize {
        self.bytes.field_size()
    }
}
impl FromFieldRepr for Nonce {
    const FIELD_SIZE: usize = <[u8; 32] as FromFieldRepr>::FIELD_SIZE;
    fn from_field_repr(r: &[Fr]) -> Option<Self> {
        if r.len() < Self::FIELD_SIZE { return None; }
        let mut _offset = 0usize;
        let bytes = <[u8; 32] as FromFieldRepr>::from_field_repr(&r[_offset.._offset + <[u8; 32] as FromFieldRepr>::FIELD_SIZE])?;
        _offset += <[u8; 32] as FromFieldRepr>::FIELD_SIZE;
        let _ = _offset;
        Some(Nonce { bytes })
    }
}

#[derive(Clone, Debug, PartialEq, Eq, Default)]
pub struct MerkleTreeDigest {
    pub field: Fr,
}
impl Aligned for MerkleTreeDigest {
    fn alignment() -> Alignment {
        Alignment::concat([&<Fr as Aligned>::alignment()])
    }
}
impl FieldRepr for MerkleTreeDigest {
    fn field_repr<W: MemWrite<Fr>>(&self, writer: &mut W) {
        self.field.field_repr(writer);
    }
    fn field_size(&self) -> usize {
        self.field.field_size()
    }
}
impl FromFieldRepr for MerkleTreeDigest {
    const FIELD_SIZE: usize = <Fr as FromFieldRepr>::FIELD_SIZE;
    fn from_field_repr(r: &[Fr]) -> Option<Self> {
        if r.len() < Self::FIELD_SIZE { return None; }
        let mut _offset = 0usize;
        let field = <Fr as FromFieldRepr>::from_field_repr(&r[_offset.._offset + <Fr as FromFieldRepr>::FIELD_SIZE])?;
        _offset += <Fr as FromFieldRepr>::FIELD_SIZE;
        let _ = _offset;
        Some(MerkleTreeDigest { field })
    }
}

#[derive(Clone, Debug, PartialEq, Eq, Default)]
pub struct zk_secret_key {
    pub bytes: [u8; 32],
}
impl Aligned for zk_secret_key {
    fn alignment() -> Alignment {
        Alignment::concat([&<[u8; 32] as Aligned>::alignment()])
    }
}
impl FieldRepr for zk_secret_key {
    fn field_repr<W: MemWrite<Fr>>(&self, writer: &mut W) {
        self.bytes.field_repr(writer);
    }
    fn field_size(&self) -> usize {
        self.bytes.field_size()
    }
}
impl FromFieldRepr for zk_secret_key {
    const FIELD_SIZE: usize = <[u8; 32] as FromFieldRepr>::FIELD_SIZE;
    fn from_field_repr(r: &[Fr]) -> Option<Self> {
        if r.len() < Self::FIELD_SIZE { return None; }
        let mut _offset = 0usize;
        let bytes = <[u8; 32] as FromFieldRepr>::from_field_repr(&r[_offset.._offset + <[u8; 32] as FromFieldRepr>::FIELD_SIZE])?;
        _offset += <[u8; 32] as FromFieldRepr>::FIELD_SIZE;
        let _ = _offset;
        Some(zk_secret_key { bytes })
    }
}

#[derive(Clone, Debug, PartialEq, Eq, Default)]
pub struct zk_public_key {
    pub bytes: [u8; 32],
}
impl Aligned for zk_public_key {
    fn alignment() -> Alignment {
        Alignment::concat([&<[u8; 32] as Aligned>::alignment()])
    }
}
impl FieldRepr for zk_public_key {
    fn field_repr<W: MemWrite<Fr>>(&self, writer: &mut W) {
        self.bytes.field_repr(writer);
    }
    fn field_size(&self) -> usize {
        self.bytes.field_size()
    }
}
impl FromFieldRepr for zk_public_key {
    const FIELD_SIZE: usize = <[u8; 32] as FromFieldRepr>::FIELD_SIZE;
    fn from_field_repr(r: &[Fr]) -> Option<Self> {
        if r.len() < Self::FIELD_SIZE { return None; }
        let mut _offset = 0usize;
        let bytes = <[u8; 32] as FromFieldRepr>::from_field_repr(&r[_offset.._offset + <[u8; 32] as FromFieldRepr>::FIELD_SIZE])?;
        _offset += <[u8; 32] as FromFieldRepr>::FIELD_SIZE;
        let _ = _offset;
        Some(zk_public_key { bytes })
    }
}

#[derive(Clone, Debug, PartialEq, Eq, Default)]
pub struct opening {
    pub bytes: [u8; 32],
}
impl Aligned for opening {
    fn alignment() -> Alignment {
        Alignment::concat([&<[u8; 32] as Aligned>::alignment()])
    }
}
impl FieldRepr for opening {
    fn field_repr<W: MemWrite<Fr>>(&self, writer: &mut W) {
        self.bytes.field_repr(writer);
    }
    fn field_size(&self) -> usize {
        self.bytes.field_size()
    }
}
impl FromFieldRepr for opening {
    const FIELD_SIZE: usize = <[u8; 32] as FromFieldRepr>::FIELD_SIZE;
    fn from_field_repr(r: &[Fr]) -> Option<Self> {
        if r.len() < Self::FIELD_SIZE { return None; }
        let mut _offset = 0usize;
        let bytes = <[u8; 32] as FromFieldRepr>::from_field_repr(&r[_offset.._offset + <[u8; 32] as FromFieldRepr>::FIELD_SIZE])?;
        _offset += <[u8; 32] as FromFieldRepr>::FIELD_SIZE;
        let _ = _offset;
        Some(opening { bytes })
    }
}


pub trait Witnesses<PS> {
    fn private_zk_secret_key<'a>(&self, ctx: &WitnessContext<Ledger<'a>, PS>) -> (PS, zk_secret_key);
    fn private_remove_coin<'a>(&self, ctx: &WitnessContext<Ledger<'a>, PS>, coin: coin_info) -> (PS, ());
    fn private_zk_public_key<'a>(&self, ctx: &WitnessContext<Ledger<'a>, PS>) -> (PS, zk_public_key);
    fn private_add_coin<'a>(&self, ctx: &WitnessContext<Ledger<'a>, PS>, coin: coin_info) -> (PS, ());
    fn context_path_of<'a>(&self, ctx: &WitnessContext<Ledger<'a>, PS>, cm: commitment) -> (PS, MerkleTreePath);
    fn context_new_coin_info<'a>(&self, ctx: &WitnessContext<Ledger<'a>, PS>) -> (PS, coin_info);
    fn context_encrypt<'a>(&self, ctx: &WitnessContext<Ledger<'a>, PS>, pk: Vec<u8>, coin: coin_info) -> (PS, Vec<u8>);
}

pub struct Contract<PS, W = NoWitnesses>
where
    W: Witnesses<PS>,
{
    pub witnesses: W,
    _ps: PhantomData<PS>,
}

impl<PS, W> Contract<PS, W>
where
    W: Witnesses<PS>,
{
    pub fn new(witnesses: W) -> Self {
        Self { witnesses, _ps: PhantomData }
    }
    pub fn initial_state(
        &self,
        ctx: ConstructorContext<PS>,
    ) -> Result<ConstructorResult<PS>, CompactError> {
        let sv = new_array(vec![
            new_map(),
            new_historic_merkle_tree(32),
            new_cell(Vec::<u8>::new()),
        ]);
        let state = ChargedState::new(sv);
        let qctx = QueryContext::new(state, ContractAddress::default());
        Ok(ConstructorResult {
            current_contract_state: qctx.state,
            current_private_state: ctx.initial_private_state,
            current_zswap_local_state: ctx.empty_zswap_local_state,
        })
    }

    pub fn spend(
        &self,
        ctx: CircuitContext<PS>,
        dest_public_key: public_key,
        input_coin: coin_info,
    ) -> Result<CircuitResults<PS, ()>, CompactError> {
        unimplemented!("M3-I3: circuit body emission for spend")
    }

    pub fn zerocash_mint(
        &self,
        ctx: CircuitContext<PS>,
    ) -> Result<CircuitResults<PS, ()>, CompactError> {
        unimplemented!("M3-I3: circuit body emission for zerocash_mint")
    }

}

pub struct Ledger<'a, D: DB = DefaultDB> {
    state: &'a ChargedState<D>,
}

pub fn ledger<D: DB>(state: &ChargedState<D>) -> Ledger<'_, D> {
    Ledger { state }
}

impl<'a, D: DB> Ledger<'a, D> {
}

pub mod pure_circuits {
}
